#!/bin/bash
# Update packages
yum update -y

# Install Apache (httpd)
yum install -y httpd

# Start & enable service
systemctl start httpd
systemctl enable httpd

# Create a sample web page
echo "<h1>Deployed using EC2 User Data Script 🎉</h1>" > /var/www/html/index.html

